/**
 * Core node type definitions for the reactive engine.
 * Nodes represent individual units of state in the engine.
 */

/**
 * Base metadata that all nodes must have.
 */
export interface NodeMetadata {
  /**
   * Unique identifier for the node.
   */
  id: string;

  /**
   * Human-readable label for the node.
   */
  label?: string;

  /**
   * Optional description of the node's purpose.
   */
  description?: string;

  /**
   * Tags for categorizing and filtering nodes.
   */
  tags?: string[];
}

/**
 * Generic node type with flexible value.
 *
 * @template TValue - The type of value this node holds (defaults to unknown for type safety)
 */
export interface Node<TValue = unknown> extends NodeMetadata {
  /**
   * The current value of this node.
   */
  value: TValue;

  /**
   * Whether this node is currently visible in the UI.
   * @default true
   */
  visible?: boolean;

  /**
   * Whether this node is currently disabled (read-only).
   * @default false
   */
  disabled?: boolean;

  /**
   * Error message if this node is in an error state.
   */
  error?: string;

  /**
   * Custom metadata for application-specific use cases.
   */
  metadata?: Record<string, unknown>;
}

/**
 * Partial update type for nodes.
 * Allows updating any subset of node properties except the id.
 *
 * @template TValue - The type of value this node holds
 */
export type NodeUpdate<TValue = unknown> = Partial<Omit<Node<TValue>, 'id'>>;

/**
 * Type guard to check if a value is a valid Node.
 */
export function isNode(value: unknown): value is Node {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value &&
    'value' in value &&
    typeof (value as Node).id === 'string'
  );
}

/**
 * Array-shaped node. Represents an ordered collection of items whose
 * IDENTITY (stable ids + order) is owned by the engine. The item VALUES
 * live outside the engine — in @dashforge/forms they live in RHF form
 * state; the engine only tracks the ordered id sequence.
 *
 * Rationale: multiple consumers (e.g. `useDashFieldArray` mounted in
 * different wizard steps) can subscribe to the SAME engine array node
 * and share stable identity across mount/unmount cycles. Without this,
 * per-hook state (as in RHF's `useFieldArray`) diverges every time a
 * step remounts.
 *
 * @template TItem - The shape of individual items. Currently informational
 *   only (the engine does not enforce or introspect item shape); reserved
 *   for future extensions that may reflect item structure into the engine.
 */
// The generic parameter is intentionally unused at the type level today —
// reserved for future array-node introspection (see JSDoc above).
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export interface ArrayNode<TItem = unknown> extends NodeMetadata {
  /**
   * Ordered list of stable item identifiers. Generated by the engine
   * at append / insert time and stable across the engine's lifetime.
   *
   * Consumers use these as React keys and as the source of truth for
   * item order (indices are derived from position in this array).
   */
  ids: string[];
}

/**
 * Type guard to check if a value is an ArrayNode.
 */
export function isArrayNode(value: unknown): value is ArrayNode {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value &&
    'ids' in value &&
    typeof (value as ArrayNode).id === 'string' &&
    Array.isArray((value as ArrayNode).ids)
  );
}
