import { useMemo } from 'react';
import { useFieldArray, type FieldArrayWithId } from 'react-hook-form';
import type { FieldValues, FieldPath } from 'react-hook-form';
import { useDashFormContext } from '../core/useDashFormContext';

/**
 * Single item in field array with metadata.
 *
 * DASHFORGE-OWNED TYPE (not RHF).
 * Stable across V1 → V3 migration.
 */
export interface DashFieldArrayItem {
  /**
   * Stable identifier for React key.
   * V1: Generated by RHF useFieldArray.
   * V3: May be generated by Engine.
   *
   * Usage: <div key={field.id}>
   */
  id: string;

  /**
   * Current position in array (0-indexed).
   * Updates when items are added/removed/moved.
   */
  index: number;

  /**
   * Full field path for registration.
   * Format: "{arrayName}.{index}"
   * Example: "users.0", "users.1"
   *
   * DX IMPROVEMENT: Pre-computed, no template string needed.
   *
   * Usage: <TextField name={`${field.name}.email`} />
   */
  name: string;

  // NO value in V1
  // NO RHF internal fields
}

/**
 * Return value from useDashFieldArray hook.
 *
 * DASHFORGE-OWNED TYPE (not RHF).
 * Stable across V1 → V3 migration.
 */
export interface UseDashFieldArrayReturn<TItem> {
  /**
   * Array of field items with metadata.
   * Updates when array operations occur.
   *
   * Use field.id as React key.
   * Use field.name for field registration.
   */
  fields: DashFieldArrayItem[];

  /**
   * Append item to end of array.
   * V1: Delegates to RHF append.
   * V3: May use Engine operations.
   *
   * @param item - Item to append
   */
  append: (item: TItem) => void;

  /**
   * Remove item at index.
   * V1: Delegates to RHF remove.
   * V3: May use Engine operations.
   *
   * @param index - Index to remove (0-based)
   */
  remove: (index: number) => void;

  /**
   * Move item from one index to another.
   * V1: Delegates to RHF move.
   * V3: May use Engine operations.
   *
   * @param from - Source index
   * @param to - Destination index
   */
  move: (from: number, to: number) => void;

  /**
   * Insert item at specific index.
   * V1: Delegates to RHF insert.
   * V3: May use Engine operations.
   *
   * @param index - Index to insert at
   * @param item - Item to insert
   */
  insert: (index: number, item: TItem) => void;

  /**
   * Replace entire array with new items.
   * V1: Delegates to RHF replace.
   * V3: May use Engine operations.
   *
   * @param items - New array of items
   */
  replace: (items: TItem[]) => void;
}

/**
 * Hook for managing dynamic field arrays.
 *
 * V1: Thin adapter over react-hook-form's useFieldArray.
 * Provides Dashforge-style API with pre-computed field names.
 *
 * PERFORMANCE: V1 matches RHF baseline plus minimal wrapper overhead.
 * Performance claims require Phase 2 benchmark results.
 *
 * V1 improves DEVELOPER EXPERIENCE, not performance.
 *
 * @example
 * ```tsx
 * interface User { name: string; email: string; }
 *
 * function UserList() {
 *   const { fields, append, remove } = useDashFieldArray<User>('users');
 *
 *   return (
 *     <>
 *       {fields.map((field) => (
 *         <div key={field.id}>
 *           <TextField name={`${field.name}.name`} />
 *           <TextField name={`${field.name}.email`} />
 *           <Button onClick={() => remove(field.index)}>Remove</Button>
 *         </div>
 *       ))}
 *       <Button onClick={() => append({ name: '', email: '' })}>Add</Button>
 *     </>
 *   );
 * }
 * ```
 *
 * @template TItem - Type of array items
 * @param name - Field array name (e.g., "users", "addresses")
 * @returns Array operations and field metadata
 */
export function useDashFieldArray<TItem>(
  name: string
): UseDashFieldArrayReturn<TItem> {
  // Get RHF instance from DashFormContext
  const { rhf } = useDashFormContext();

  // Delegate to RHF useFieldArray
  // LOCALIZED CAST: RHF requires FieldPath<FieldValues>, we accept string for DX
  // This cast does NOT leak to public API
  const {
    fields: rhfFields,
    append,
    remove,
    move,
    insert,
    replace,
  } = useFieldArray<FieldValues, FieldPath<FieldValues>>({
    control: rhf.control,
    name: name as FieldPath<FieldValues>,
  });

  // Transform RHF fields to Dashforge format
  // DX improvement: pre-compute field.name path
  // FIELD MAPPING STABILITY: useMemo to avoid unnecessary re-computation
  const fields: DashFieldArrayItem[] = useMemo(() => {
    return rhfFields.map((field: FieldArrayWithId, index: number) => ({
      id: field.id, // RHF stable ID
      index, // Current position
      name: `${name}.${index}`, // Pre-computed path (DX improvement)
    }));
  }, [rhfFields, name]);

  // Return Dashforge-style API
  // LOCALIZED CASTS: RHF generic methods cast to match public signature
  // These casts do NOT leak to public API
  return {
    fields, // Dashforge type
    append: append as (item: TItem) => void, // Cast for public signature
    remove, // No cast needed
    move, // No cast needed
    insert: insert as (index: number, item: TItem) => void, // Cast for public signature
    replace: replace as (items: TItem[]) => void, // Cast for public signature
  };
}
