import { useCallback, useMemo, useState, useSyncExternalStore } from 'react';
import { snapshot } from 'valtio';
import type { FieldValues, FieldPath } from 'react-hook-form';
import { useDashFormContext } from '../core/useDashFormContext';

/**
 * Referentially-stable empty ids array. Reused across every hook
 * instance that has no engine array node yet so that
 * `useSyncExternalStore` sees a stable reference and does not tear.
 */
const EMPTY_IDS: readonly string[] = Object.freeze([]);

/**
 * Single item in field array with metadata.
 *
 * DASHFORGE-OWNED TYPE (not RHF).
 */
export interface DashFieldArrayItem {
  /**
   * Stable identifier for React key. Generated by the Dashforge Engine
   * (format `_arr_<n>`, opaque — do not parse or persist). Stable
   * within the engine's lifetime — across mount / unmount cycles of
   * the hook itself (wizard steps, conditional rendering, tab
   * navigation). Two instances of `useDashFieldArray('items')` mounted
   * at different times see the same ids for the same items.
   *
   * Usage: `<div key={field.id}>`
   */
  id: string;

  /**
   * Current position in array (0-indexed).
   * Updates when items are added / removed / moved.
   */
  index: number;

  /**
   * Full field path for registration.
   * Format: `<arrayName>.<index>` — e.g. `users.0`, `users.1`.
   *
   * Usage: `<TextField name={`${field.name}.email`} />`
   */
  name: string;
}

/**
 * Return value from useDashFieldArray hook.
 *
 * DASHFORGE-OWNED TYPE (not RHF).
 */
export interface UseDashFieldArrayReturn<TItem> {
  /**
   * Array of field items with metadata.
   * Updates when array operations occur.
   *
   * Use `field.id` as React key.
   * Use `field.name` for field registration.
   */
  fields: DashFieldArrayItem[];

  /**
   * Append item to end of array.
   */
  append: (item: TItem) => void;

  /**
   * Remove item at index. Out-of-range index is a no-op.
   */
  remove: (index: number) => void;

  /**
   * Move item from one index to another. Out-of-range or same-index is
   * a no-op (item id preserved).
   */
  move: (from: number, to: number) => void;

  /**
   * Insert item at a specific index. Index is clamped to
   * `[0, fields.length]`.
   */
  insert: (index: number, item: TItem) => void;

  /**
   * Replace entire array with new items. Regenerates all ids —
   * every React key changes, so React remounts every rendered item.
   */
  replace: (items: TItem[]) => void;
}

/**
 * Hook for managing dynamic field arrays with engine-owned identity.
 *
 * ## Architecture
 *
 * Identity (ordered ids) lives on the Dashforge Engine, values live in
 * react-hook-form. The two are synchronised inside every operation:
 *
 * 1. Mutate the engine array node (ids)
 * 2. Mutate the corresponding RHF array (values)
 * 3. Notify reactions watching the array root through the adapter
 *
 * The hook subscribes reactively to engine changes via
 * `useSyncExternalStore` wired to `adapter.notifyValueChange` — every
 * consumer of `useDashFieldArray('items')` reads the SAME engine
 * array node, so multiple instances mounted across wizard steps,
 * tabs, or conditional regions share the same ordered ids. This is
 * the property RHF's per-hook `useFieldArray` cannot deliver, and
 * the fix for the multi-step-wizard fault-line
 * (`/fault-lines/usefieldarray-multi-step-wizards`).
 *
 * ## Contract
 *
 * - `field.id` is stable across mount / unmount cycles of the hook.
 * - `field.id` is NOT stable across `replace()` (regeneration is
 *   intentional).
 * - `field.id` is NOT persistable — do not serialise or send to
 *   another session.
 * - The hook writes to RHF via `rhf.setValue`; it does NOT go through
 *   the input `wrappedOnChange` path. Reactions watching the array
 *   root fire via `adapter.notifyValueChange`.
 * - Consumer boundary: for internal consistency, prefer the hook's
 *   own operations (`append` / `remove` / `move` / `insert` /
 *   `replace`) over calling `rhf.setValue` on the array root through
 *   `useDashFormContext().rhf`. Direct `rhf.setValue` on an array
 *   root bypasses the engine — reactions won't fire and ids won't
 *   reconcile until the next hook operation on that array.
 *
 * @example
 * ```tsx
 * interface User { name: string; email: string; }
 *
 * function UserList() {
 *   const { fields, append, remove } = useDashFieldArray<User>('users');
 *
 *   return (
 *     <>
 *       {fields.map((field) => (
 *         <div key={field.id}>
 *           <TextField name={`${field.name}.name`} />
 *           <TextField name={`${field.name}.email`} />
 *           <Button onClick={() => remove(field.index)}>Remove</Button>
 *         </div>
 *       ))}
 *       <Button onClick={() => append({ name: '', email: '' })}>Add</Button>
 *     </>
 *   );
 * }
 * ```
 *
 * @template TItem - Type of array items.
 * @param name - Field array name (e.g. `"users"`, `"user.addresses"`).
 */
export function useDashFieldArray<TItem>(
  name: string
): UseDashFieldArrayReturn<TItem> {
  const { engine, rhf, adapter } = useDashFormContext();

  // Lazy-init: register the engine array node exactly once per hook
  // instance IF it doesn't already exist. `useState`'s init callback
  // runs exactly once per component instance even under React
  // StrictMode double-render.
  //
  // If the array node already exists (registered by a sibling
  // `useDashFieldArray('users')` in another mounted step), this hook
  // just subscribes to it — the whole point of engine-owned identity.
  //
  // We seed the initial id count from RHF's current value at this
  // path so `defaultValues.users = [{...}, {...}]` produces two ids
  // that align 1:1 with the two initial items.
  useState(() => {
    if (!engine.getArrayNode(name)) {
      const currentValue = rhf.getValues(name as FieldPath<FieldValues>);
      const initialCount = Array.isArray(currentValue)
        ? currentValue.length
        : 0;
      engine.registerArrayNode(name, initialCount);
    }
    return null;
  });

  // Reactive subscription. `useSyncExternalStore` is the canonical
  // sync-friendly primitive — mirrors the pattern of
  // `useDashFieldMeta` and `useFieldRuntime` in this same package.
  //
  // We route the subscription through `adapter.addOnValueSyncListener`
  // (which fires synchronously — see FormEngineAdapter.notifyValueChange)
  // and filter by field name. Every array-mutation operation in this
  // hook ends with `adapter.notifyValueChange(name)`, so writes made
  // from any mounted instance of this hook propagate to every other
  // subscribed instance in the same commit.
  //
  // The snapshot itself is read via Valtio's `snapshot()` — that
  // function does structural sharing, so `snapshot(...)[name]?.ids`
  // returns the SAME array reference when the underlying ids haven't
  // changed, which is what `useSyncExternalStore` needs to avoid
  // tearing.
  const subscribe = useCallback(
    (onChange: () => void) =>
      adapter.addOnValueSyncListener((fieldName) => {
        if (fieldName === name) onChange();
      }),
    [adapter, name]
  );

  const getSnapshot = useCallback((): readonly string[] => {
    const snap = snapshot(engine.getState().arrayNodes);
    return snap[name]?.ids ?? EMPTY_IDS;
  }, [engine, name]);

  const ids = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  // Pre-compute fields metadata for the consumer. The useMemo dep
  // list ensures fields is identity-stable when `ids` and `name` are
  // unchanged.
  const fields: DashFieldArrayItem[] = useMemo(
    () =>
      ids.map((id, index) => ({
        id,
        index,
        name: `${name}.${index}`,
      })),
    [ids, name]
  );

  // Helpers — read / write RHF's array value at `name`.
  const getRhfArray = useCallback((): TItem[] => {
    const v = rhf.getValues(name as FieldPath<FieldValues>);
    return Array.isArray(v) ? (v as TItem[]) : [];
  }, [name, rhf]);

  const setRhfArray = useCallback(
    (next: TItem[]) => {
      rhf.setValue(name as FieldPath<FieldValues>, next as never);
    },
    [name, rhf]
  );

  // Operations. Each mutates RHF first (so any downstream watcher of
  // the raw form value sees it), then the engine (so ids update),
  // then notifies reactions watching the array root through the
  // adapter — which is also what triggers this hook's own
  // `useSyncExternalStore` to re-read the snapshot and re-render.
  const append = useCallback(
    (item: TItem) => {
      setRhfArray([...getRhfArray(), item]);
      engine.appendArrayItem(name);
      adapter.notifyValueChange(name);
    },
    [engine, adapter, name, getRhfArray, setRhfArray]
  );

  const remove = useCallback(
    (index: number) => {
      const current = getRhfArray();
      if (index < 0 || index >= current.length) {
        return;
      }
      setRhfArray(current.filter((_, i) => i !== index));
      engine.removeArrayItem(name, index);
      adapter.notifyValueChange(name);
    },
    [engine, adapter, name, getRhfArray, setRhfArray]
  );

  const move = useCallback(
    (from: number, to: number) => {
      const current = getRhfArray();
      const len = current.length;
      if (from < 0 || from >= len || to < 0 || to >= len || from === to) {
        return;
      }
      const next = [...current];
      const [movedItem] = next.splice(from, 1) as [TItem, ...TItem[]];
      next.splice(to, 0, movedItem);
      setRhfArray(next);
      engine.moveArrayItem(name, from, to);
      adapter.notifyValueChange(name);
    },
    [engine, adapter, name, getRhfArray, setRhfArray]
  );

  const insert = useCallback(
    (index: number, item: TItem) => {
      const current = getRhfArray();
      const clampedIndex = Math.max(0, Math.min(index, current.length));
      const next = [...current];
      next.splice(clampedIndex, 0, item);
      setRhfArray(next);
      engine.insertArrayItem(name, clampedIndex);
      adapter.notifyValueChange(name);
    },
    [engine, adapter, name, getRhfArray, setRhfArray]
  );

  const replace = useCallback(
    (items: TItem[]) => {
      setRhfArray(items);
      engine.replaceArrayItems(name, items.length);
      adapter.notifyValueChange(name);
    },
    [engine, adapter, name, setRhfArray]
  );

  return {
    fields: fields as DashFieldArrayItem[],
    append,
    remove,
    move,
    insert,
    replace,
  };
}
