/**
 * Post-build .d.ts flattener.
 *
 * `@nx/rollup` (or `@nx/js/typescript` — exact owner is fuzzy) emits a
 * `dist/index.d.ts` wrapper that contains a single line:
 *
 *   export * from "./src/index";
 *
 * Consumers of THIS workspace that import via TypeScript project
 * references (e.g., `@dashforge/tw` → `@dashforge/forms`) hit a known
 * TS bug under `moduleResolution: "bundler"` where `export *` in a
 * dist-wrapper drops a subset of re-exports — most notably
 * `useDashFieldMeta` — causing TS2305 "no exported member" errors on
 * the downstream typecheck.
 *
 * Fix: replace the wrapper with EXPLICIT re-exports derived from the
 * true `.d.ts` payload (`dist/src/index.d.ts`). Path rewriting:
 *
 *   from './core/foo'      → from './src/core/foo'
 *   from '@dashforge/x'    → from '@dashforge/x'      (unchanged)
 *
 * Idempotent — safe to run multiple times.
 *
 * Hook: invoked from `rollup.config.cjs` via the `writeBundle` plugin
 * lifecycle so it runs at the end of every `nx build @dashforge/forms`.
 */
const fs = require('node:fs');
const path = require('node:path');

function flattenDts(packageDir) {
  const distRoot = path.join(packageDir, 'dist');
  const wrapper = path.join(distRoot, 'index.d.ts');
  const real = path.join(distRoot, 'src', 'index.d.ts');

  if (!fs.existsSync(real)) {
    // Build produced no `dist/src/index.d.ts` — nothing to flatten.
    return;
  }
  const content = fs.readFileSync(real, 'utf8');

  // Rewrite relative module specifiers (`./xxx`, `../xxx`) so they
  // resolve correctly when the wrapper lives one directory up.
  //   ./foo            → ./src/foo
  //   ./foo/bar.js     → ./src/foo/bar.js
  //   ../foo           → ./foo            (one dir up cancels)
  // Bare specifiers (`@dashforge/...`, `react`, ...) pass through.
  const rewritten = content
    .replace(/from\s+(['"])\.\//g, "from $1./src/")
    .replace(/from\s+(['"])\.\.\//g, "from $1./");

  // Drop the sourcemap pragma — it points at index.d.ts.map relative
  // to dist/src/, which isn't true anymore from dist/.
  const final = rewritten.replace(/\/\/# sourceMappingURL=.*$/m, '');

  // Preserve the wrapper's banner so consumers see "auto-generated".
  const header =
    `// ───── AUTO-GENERATED by scripts/flat-dts.cjs ─────\n` +
    `// Replaces a fragile \`export *\` wrapper with explicit re-exports\n` +
    `// to work around a TS bundler+project-references bug.\n` +
    `// Source: dist/src/index.d.ts (edit there, this file is regenerated).\n\n`;

  fs.writeFileSync(wrapper, header + final, 'utf8');
}

module.exports = { flattenDts };

// Allow direct CLI invocation: `node scripts/flat-dts.cjs`.
if (require.main === module) {
  // When run directly, assume cwd is the package root.
  flattenDts(process.cwd());
   
  console.log('[flat-dts] flattened', process.cwd());
}
